t

diff --git a/start-hadoop b/start-hadoop
--- a/start-hadoop
+++ b/start-hadoop
@@ -1,16 +1,16 @@
 #!/usr/bin/env bash
 set -x
-# Check user environment variable
-if [[ -z "${HDFS_USER}" ]]; then
-  echo "Missing HDFS_USER environment variable" >&2
-  exit 1
-fi
-# Set HADOOP_USER_NAME environment vairable
-HADOOP_USER_NAME="${HDFS_USER}"
-echo "export  HADOOP_USER_NAME=\"${HDFS_USER}\"" >> /etc/bash.bashrc
-# Create user for HDFS
-adduser -S -D -H -g "" $HDFS_USER
-addgroup $HDFS_USER
+# # Check user environment variable
+# if [[ -z "${HDFS_USER}" ]]; then
+#   echo "Missing HDFS_USER environment variable" >&2
+#   exit 1
+# fi
+# # Set HADOOP_USER_NAME environment vairable
+# export HADOOP_USER_NAME="${HDFS_USER}"
+# # echo "export  HADOOP_USER_NAME=\"${HDFS_USER}\"" >> /etc/bash.bashrc
+# # Create user for HDFS
+# adduser -S -D -H -g "" $HDFS_USER
+# addgroup $HDFS_USER
 # Fix directory permissions
 chown -R $HDFS_USER:$HDFS_USER /opt/hdfs
 chown -R $HDFS_USER:$HDFS_USER $HADOOP_HOME
